version: "3"

services: 
  app:
    container_name: app_container
    build: .
    command: sh ./docker-start.sh
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
      - storage_api:/usr/src/app/node_modules
    depends_on:
      - postgres

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB_NAME}      
    volumes:
       - storage_db:/var/lib/postgres/data
    ports:
      - "5432:5432"

volumes:
    storage_db:
    storage_api: